/**
 * Original 12×12 item icons, drawn onto a 16×16 glossy panel by sprites.ts.
 */

export const ITEM_PALETTE: Record<string, string> = {
  k: '#000000',
  w: '#ffffff',
  r: '#e82818',
  R: '#a01008',
  o: '#ff9010',
  y: '#ffe040',
  Y: '#c09000',
  b: '#202038',
  B: '#6068b0',
  n: '#8a4a1c',
  N: '#d08a48',
  g: '#707080',
  G: '#c8c8d8',
  L: '#2f6ae8',
  l: '#8ec0ff',
  e: '#2aa02a',
  E: '#90e070',
  p: '#ff5aa0',
  P: '#b02060',
  s: '#ffc890',
  v: '#8040c0',
  V: '#c090ff',
  c: '#40d0d0',
};

export const ITEM_ICONS: Record<string, string[]> = {
  bomb: [
    '.......k.y..',
    '......kNkyo.',
    '....kkkk..y.',
    '..kkbbbbkk..',
    '.kbBBbbbbbk.',
    '.kbBbbbbbbk.',
    'kbbbbbbbbbbk',
    'kbbbbbbbbbbk',
    '.kbbbbbbbbk.',
    '.kbbbbbbbbk.',
    '..kkbbbbkk..',
    '....kkkk....',
  ],
  fire: [
    '.....k......',
    '....krk.....',
    '...krrk..k..',
    '..krork.krk.',
    '..kroorkrrk.',
    '.krooyorork.',
    '.kroyyyoork.',
    'kroyywyyork.',
    'kroywwwyyork',
    'kroyywwyyork',
    '.krooyyoork.',
    '..kkkkkkkk..',
  ],
  speed: [
    '....kkkk....',
    '...kLLLLk...',
    '...kLlLLk...',
    '...kLlLLk...',
    '...kLLLLkkk.',
    '...kLLLLLLLk',
    '..kLLLLLLLLk',
    '..kwwwwwwwwk',
    '..kkkkkkkkkk',
    '...kgk..kgk.',
    '..kgGk..kgGk',
    '...kk....kk.',
  ],
  remote: [
    '.....kk.....',
    '....kyyk....',
    '.....kk.....',
    '.....kk.....',
    '...kkkkkk...',
    '..kggggggk..',
    '..kgrrrrgk..',
    '..kgrRRrgk..',
    '..kgrrrrgk..',
    '..kggggggk..',
    '..kgGGGGgk..',
    '...kkkkkk...',
  ],
  wallpass: [
    'kkkkkkkkkkkk',
    'kNNNkNNNNNkk',
    'knnnknnnnnkk',
    'kkkkkkkkkkkk',
    'kNNk.lll.Nkk',
    'knnkllllllkk',
    'kkkklkllkkkk',
    'kNNNlllllNkk',
    'knnnnlllnnkk',
    'kkkkkkkkkkkk',
    'kNNNNNkNNNkk',
    'kkkkkkkkkkkk',
  ],
  bombpass: [
    '......k.y...',
    '.....kNkyo..',
    '...kkkk..y..',
    '.kkbbbbkk...',
    'kbBBbbbbbk..',
    'kbBbllllbbk.',
    'kbbllwllllk.',
    'kbbllllllbk.',
    '.kbbbllllk..',
    '.kbbbbbbbk..',
    '..kkbbbbkk..',
    '....kkkk....',
  ],
  fireman: [
    '...kkkkkk...',
    '..kLLLLLLk..',
    '.kLlLLLLLLk.',
    '.kLlLkkLLLk.',
    '.kLLkrrkLLk.',
    '.kLkroorkLk.',
    '.kLkoyyokLk.',
    '.kLLkyykLLk.',
    '..kLLkkLLk..',
    '...kLLLLk...',
    '....kLLk....',
    '.....kk.....',
  ],
  flak: [
    '..kkk..kkk..',
    '.kyyyk.kyyk.',
    '.kyYyykkyyk.',
    'kyYyyyyyyyyk',
    'kyYyykkyyyyk',
    'kyYyk..kyyyk',
    'kyYyk..kyyyk',
    'kyYyykkyyyyk',
    'kyYyyyyyyyyk',
    'kyYyyyyyyyyk',
    '.kYYYYYYYYk.',
    '..kkkkkkkk..',
  ],
  kick: [
    '............',
    '..kkkk......',
    '..kLLk......',
    '..kLLk......',
    '..kLLk......',
    '..kLLkkkkk..',
    '..kLLLLLLLk.',
    '.kLlLLLLLLLk',
    '.kLLLLLLLLLk',
    '.kkkkkkkkkkk',
    '.kwwwwwwwwwk',
    '..kkkkkkkkk.',
  ],
  punch: [
    '............',
    '...kkkkk....',
    '..kppppppk..',
    '.kpwpppppkk.',
    '.kppkpkpkpk.',
    '.kpppppppppk',
    '.kppppppppk.',
    '..kpppppppk.',
    '...kkpppkk..',
    '....kGGGk...',
    '....kgggk...',
    '.....kkk....',
  ],
  push: [
    '............',
    '..kkkk......',
    '.kppppk.kk..',
    '.kpwpppkpk..',
    '.kpppppppk..',
    '.kppppppk...',
    '.kppppppk.k.',
    '..kpppppkkok',
    '...kpppk.ko.',
    '...kGGGk..k.',
    '...kgggk....',
    '....kkk.....',
  ],
  glove: [
    '..k.k.k.....',
    '.kwkwkwk.k..',
    '.kwkwkwkkwk.',
    '.kwkwkwkkwk.',
    '.kwwwwwkwwk.',
    '.kwwwwwwwwk.',
    '.kwwwwwwwk..',
    '..kwwwwwwk..',
    '..kkwwwwk...',
    '...kLLLLk...',
    '...kLllLk...',
    '....kkkk....',
  ],
  skull: [
    '...kkkkkk...',
    '..kwwwwwwk..',
    '.kwwwwwwwwk.',
    '.kwkkwwkkwk.',
    '.kwkkwwkkwk.',
    '.kwwwkkwwwk.',
    '..kwwwwwwk..',
    '...kwkwkwk..',
    '...kkkkkkk..',
    '....kwkwk...',
    '.....kkk....',
    '............',
  ],
  fullfire: [
    '..k..k...k..',
    '.kyk.kk.kyk.',
    '.kyykrrkkyk.',
    'kroyyrrryyk.',
    'kroyyoyoork.',
    'kroyywyyoork',
    'kroywwwwyork',
    'kroywwwwyork',
    '.kroywwyork.',
    '.kkkkkkkkkk.',
    '.kyykyykyyk.',
    '.kkkkkkkkkk.',
  ],
  heart: [
    '............',
    '.kkk...kkk..',
    'krrrk.krrrk.',
    'krwrrkrrrrk.',
    'krrrrrrrrrk.',
    'krrrrrrrrrk.',
    '.krrrrrrrk..',
    '..krrrrrk...',
    '...krrrk....',
    '....krk.....',
    '.....k......',
    '............',
  ],
  line: [
    '............',
    '..k.y.......',
    '.kNkyo......',
    'kkkk........',
    'kbbk.kbk.kbk',
    'kbBk.kbk.kbk',
    'kbbk.kbk.kbk',
    'kkkk.kkk.kkk',
    '............',
    '.kkkkkkkkkk.',
    '.krrrrrrrrrk',
    '.kkkkkkkkkk.',
  ],
  pierce: [
    '......k.y...',
    '.....kNkyo..',
    '...kkkk..y..',
    '.kkvvvvkk...',
    'kvVVvvvvvk..',
    'kvVvvvvvvk..',
    'kvvvvvvvvvk.',
    'kvvvvwvvvvk.',
    '.kvvvvvvvk..',
    '.kvvvvvvvk..',
    '..kkvvvvkk..',
    '....kkkk....',
  ],
  powerbomb: [
    '......k.y...',
    '.....kNkyo..',
    '...kkkk..y..',
    '.kkrrrrkk...',
    'krwwrrrrrk..',
    'krwrkkkkrrk.',
    'krrrkwwkrrk.',
    'krrrkkkkrrk.',
    '.krrkrrrrk..',
    '.krrkrrrrk..',
    '..kkrrrrkk..',
    '....kkkk....',
  ],
  rubber: [
    '......k.y...',
    '.....kNkyo..',
    '...kkkk..y..',
    '.kkeeeekk...',
    'keEEeeeeek..',
    'keEeeeeeeek.',
    'keeekeekeek.',
    'keeeeeeeeek.',
    '.keekkkkek..',
    '.keeeeeeek..',
    '..kkeeeekk..',
    '....kkkk....',
  ],
  mine: [
    '............',
    '............',
    '....kkkk....',
    '...krrrrk...',
    '..krwrrrrk..',
    '.kkkkkkkkkk.',
    'kggggggggggk',
    'kgGGGGGGGGgk',
    'kggggggggggk',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  egg: [
    '....kkkk....',
    '...kwwwwk...',
    '..kwwwwwwk..',
    '..kwGwwwwk..',
    '.kwwwwwwwwk.',
    '.kwwwneewwk.',
    '.kwwneeewwk.',
    '.kwwwwnewwk.',
    '.kwwwwwwwwk.',
    '..kwwwwwwk..',
    '...kkwwkk...',
    '.....kk.....',
  ],
  geta: [
    '............',
    '............',
    '..kkkkkkkk..',
    '..kGGGGGGk..',
    '..kkkGGkkk..',
    '....kGGk....',
    'kkkkkkkkkkkk',
    'kgGGGGGGGGgk',
    'kggggggggggk',
    'kkkkkkkkkkkk',
    '..kgk..kgk..',
    '..kkk..kkk..',
  ],
  // Hidden score panels ---------------------------------------------------------------
  secret_b: [
    'kkkkkkkkkkkk',
    'kyyyyyyyyyyk',
    'kyrrrrrrryyk',
    'kyrrwwwwrryk',
    'kyrrwrrrwryk',
    'kyrrwwwwrryk',
    'kyrrwrrrwryk',
    'kyrrwrrrwryk',
    'kyrrwwwwrryk',
    'kyrrrrrrrryk',
    'kyyyyyyyyyyk',
    'kkkkkkkkkkkk',
  ],
  secret_louie: [
    '..kk....kk..',
    '.knnk..knnk.',
    '.knNk..kNnk.',
    '..knkkkknk..',
    '.knnnnnnnnk.',
    'knnkwnnkwnnk',
    'knnkknnkknnk',
    'knnnnkknnnnk',
    '.knNNNNNNnk.',
    '.knNNkkNNnk.',
    '..knnnnnnk..',
    '...kkkkkk...',
  ],
  secret_yoyo: [
    '.....k......',
    '.....k......',
    '.....k......',
    '...kkkkk....',
    '..krrrrrk...',
    '.krwrrrrrk..',
    '.krrkkkrrk..',
    '.krrkykrrk..',
    '.krrkkkrrk..',
    '.krrrrrrrk..',
    '..krrrrrk...',
    '...kkkkk....',
  ],
  secret_golden: [
    '.....kk.....',
    '....kyyk....',
    '...kkkkkk...',
    '..kyyyyyyk..',
    '.kyYyyyyyyk.',
    '.kyykkkkyyk.',
    '.kykwyywkyk.',
    '.kykyyyykyk.',
    '.kyykkkkyyk.',
    '..kyyyyyyk..',
    '..kYkkkkYk..',
    '..kk....kk..',
  ],
  secret_nakamoto: [
    '...kkkkkk...',
    '..knnnnnnk..',
    '.knnnnnnnnk.',
    '.kssssssssk.',
    '.kkkkskkkkk.',
    '.kwwkskwwkk.',
    '.kkkkskkkkk.',
    '.kssssssssk.',
    '.ksskkkkssk.',
    '..ksssssk...',
    '...kkkkk....',
    '............',
  ],
  secret_angel: [
    '....kyyk....',
    '...k....k...',
    '....kkkk....',
    'kk.kwwwwk.kk',
    'kwkkwkkwkkwk',
    'kwwkwwwwkwwk',
    '.kwkkwwkkwk.',
    '..kkwwwwkk..',
    '...kwwwwk...',
    '...kwwwwk...',
    '...kk..kk...',
    '............',
  ],
};
